### ISSUE TITLE
line 216: wdiff: command not found

### ISSUE THREAD

**Issue by prankurgit** [junghans/cwdiff#9]
the wdiff command is not found in the cwdiff

$hg wdiff

**Comment by junghans** [comment]
Make sure you have the `wdiff` binary installed!

**Comment by prankurgit** [comment]
thanks mate. You were right I did not installed the wdiff.
A follow up question the hg log -pr revid does not display the word diff. 
I wanted to see this effect in the hg log -p command .. is it possible somehow?
